// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: 004_getChat.sql

package database

import (
	"context"
)

const getChatByChatId = `-- name: GetChatByChatId :one
SELECT id, createdby, lastmessage, participants, created_at, is_group_chat FROM chats WHERE id= ?
`

func (q *Queries) GetChatByChatId(ctx context.Context, id string) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChatByChatId, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Createdby,
		&i.Lastmessage,
		&i.Participants,
		&i.CreatedAt,
		&i.IsGroupChat,
	)
	return i, err
}
