// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"
)

type Chat struct {
	ID           string
	Createdby    sql.NullString
	Lastmessage  sql.NullString
	Participants sql.NullString
	CreatedAt    time.Time
	IsGroupChat  sql.NullBool
}

type User struct {
	ID        string
	Firstname sql.NullString
	Lastname  sql.NullString
	Email     string
	Password  string
}
